cache:
  type: simple
elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

keycloak:
  client-id: fc3-app
  client-secret: secret
  realm: test
  host: "http://localhost:${wiremock.server.port:8001}"

logging:
  level:
    ROOT: info

rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  categories:
    read-timeout: 2000
  genres:
    read-timeout: 2000
  videos:
    read-timeout: 2000
  keycloak:
    read-timeout: 2000




