elasticsearch:
  uris: ${ELASTICSEARCH_URIS}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  realm: ${KEYCLOAK_REALM:fc3-codeflix}
  host: ${KEYCLOAK_HOST:http://localhost:8443}

rest-client:
  keycloak:
    read-timeout: 1000